# llm-service-monitoring/templates/servicemonitor.yaml
{{- if .Values.alerts.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: llm-service-alerts
  labels:
    app: llm-service
    release: {{ .Values.release | default "prometheus" }}
spec:
  groups:
    - name: llm.rules
      rules:
        # {{ .Values.alerts.high5xxRate.duration }} 동안 초당 {{ .Values.alerts.high5xxRate.threshold }}건 이상의 5xx 오류가 발생하면 경고
        - alert: HighLLM5xxRate
          expr: sum(rate(http_server_requests_seconds_count{job="llm-service", status=~"5.."}[1m])) > {{ .Values.alerts.high5xxRate.threshold }}
          for: {{ .Values.alerts.high5xxRate.duration }}
          labels:
            severity: {{ .Values.alerts.high5xxRate.severity }}
          annotations:
            summary: "5xx 오류 비율 초과"
            description: "최근 {{ .Values.alerts.high5xxRate.duration }} 동안 llm-service에서 초당 평균 {{ .Values.alerts.high5xxRate.threshold }}건 이상의 5xx 오류가 발생했습니다."

        # {{ .Values.alerts.highLatency.duration }} 동안 p95 응답 시간이 {{ .Values.alerts.highLatency.threshold }}초 초과 시 경고
        - alert: HighLLMLatency
          expr: histogram_quantile(0.95, sum(rate(http_server_requests_seconds_bucket{job="llm-service"}[1m])) by (le)) > {{ .Values.alerts.highLatency.threshold }}
          for: {{ .Values.alerts.highLatency.duration }}
          labels:
            severity: {{ .Values.alerts.highLatency.severity }}
          annotations:
            summary: "응답 지연 초과"
            description: "최근 {{ .Values.alerts.highLatency.duration }} 동안 llm-service의 요청 중 상위 95%의 응답시간이 {{ .Values.alerts.highLatency.threshold }}초를 초과했습니다."

        # {{ .Values.alerts.trafficSpike.duration }} 동안 초당 요청 수가 {{ .Values.alerts.trafficSpike.threshold }}건 초과 시 경고
        - alert: SuddenTrafficSpike
          expr: sum(rate(http_server_requests_seconds_count{job="llm-service"}[1m])) > {{ .Values.alerts.trafficSpike.threshold }}
          for: {{ .Values.alerts.trafficSpike.duration }}
          labels:
            severity: {{ .Values.alerts.trafficSpike.severity }}
          annotations:
            summary: "요청량 급증"
            description: "llm-service에 대한 요청이 초당 {{ .Values.alerts.trafficSpike.threshold }}건을 초과하고 있으며, 해당 현상이 {{ .Values.alerts.trafficSpike.duration }} 이상 지속되고 있습니다. 부하 테스트 또는 트래픽 폭주일 수 있습니다."

        # {{ .Values.alerts.crashLooping.duration }} 동안 컨테이너 재시작 수가 {{ .Values.alerts.crashLooping.threshold }}회 초과 시 경고
        - alert: LLMPodCrashLooping
          expr: increase(kube_pod_container_status_restarts_total{namespace="llm-service"}[5m]) > {{ .Values.alerts.crashLooping.threshold }}
          for: {{ .Values.alerts.crashLooping.duration }}
          labels:
            severity: {{ .Values.alerts.crashLooping.severity }}
          annotations:
            summary: "Pod 재시작 반복 감지"
            description: "llm-service 네임스페이스에서 최근 {{ .Values.alerts.crashLooping.duration }} 동안 컨테이너 재시작이 {{ .Values.alerts.crashLooping.threshold }}회 이상 발생하고 있습니다. CrashLoopBackOff 가능성이 있습니다."
{{- end }}