# admin-service-monitoring/values.yaml

release: prometheus

alerts: 
  enabled: true
  
  # 기본 서비스 모니터링 알림 (warning/info)
  serviceAlerts:
    high5xxRate:
      duration: 2m 
      severity: warning
      threshold: 5
    highLatency: 
      duration: 2m
      severity: warning 
      threshold: 1
    trafficSpike:
      duration: 1m
      severity: info
      threshold: 100
  
  # 중요 알림 (critical)
  criticalAlerts:
    crashLooping:
      duration: 2m
      severity: critical 
      threshold: 5

serviceMonitor: 
  enabled: true
  port: http
  path: /actuator/prometheus
  interval: 30s
  scrapeTimeout: 10s
  matchLabels:
    app: admin-service