# llm-service-monitoring/values.yaml

release: prometheus

alerts: 
  enabled: true
  high5xxRate:
    duration: 2m 
    severity: warning
    threshold: 5
  highLatency: 
    duration: 2m
    severity: warning 
    threshold: 1
  trafficSpike:
    duration: 1m
    severity: info
    threshold: 100 
  crashLooping:
    duration: 2m
    severity: critical 
    threshold: 5

serviceMonitor: 
  enabled: true
  port: http
  path: /actuator/prometheus
  interval: 30s
  scrapeTimeout: 10s
  matchLabels:
    app: llm-service